### ISSUE TITLE
Problem 5: Compile time error

### ISSUE THREAD

**Issue by myilkova** [wckd-area/programming-fundamentals#1]
judge returned Compile time error on submitting  05. Character Stats solution. 
It's probably caused by difference in the var names.
We try to write to console var "name" which was read from the console as "nameOfPerson"
![issue_problem 5_compile time error](https://user-images.githubusercontent.com/14124845/37255652-04aa5526-2558-11e8-9e38-47f934248966.png)

**Comment by EkaterinKostadinov** [comment]
Issue Resolved

**Comment by myilkova** [comment]
Checked and confirmed
