### ISSUE TITLE
Submission error

### ISSUE THREAD

**Issue by aquaruiz** [wckd-area/programming-fundamentals#2]
[Problem 3](https://github.com/wckd-area/programming-fundamentals/blob/master/intro-and-basic-syntax/exercise/03.MilesToKilometers/03.MilesToKilometers)

Judge submit error: "No valid class found!".

**Comment by myilkova** [comment]
Resolved. I renamed the class. 
The source file didn't have extension. I added an extension .java. 
Also I src and out directories, moved the source file to src. 
Also I configured an intellij project module to use jdk, etc.
